#!/usr/bin/env python

import rospy
import yaml
import numpy as np
from turtlebot_mpc.turtle_bot_mpc import TurtleBotMPC

def main():
   rospy.init_node('turtlebot_mpc_node')
   
   cfg_file_path = rospy.get_param("~mpc_config_path")
   cfg = {}
   with open(cfg_file_path, 'r') as stream:
      cfg = yaml.safe_load(stream)

   mpc = TurtleBotMPC(cfg)
   
   rate = 1.0 / cfg['mpc']['T']
   ros_rate = rospy.Rate(rate)
   while not rospy.is_shutdown():
      mpc.run_controller()
      ros_rate.sleep()

if __name__ == "__main__":
   main()
